services:
  api:
    build: .
    container_name: backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgis/postgis:17-3.5

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: labourbaba

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: redis

    # BullMQ REQUIRES noeviction to prevent silent job loss under memory pressure.
    # See: https://docs.bullmq.io/guide/connections#notes-about-connection-options
    command: >
      redis-server
      --maxmemory-policy noeviction
      --save ""

    ports:
      - "6379:6379"

volumes:
  postgres_data:
