const fs = require('fs');
const path = require('path');

const features = [
  // ----------------------------------------------------
  // A. AUTHENTICATION & IDENTITY
  // ----------------------------------------------------
  {
    id: 'AUTH-001',
    name: 'Customer Registration & Profile Bootstrap',
    category: 'Authentication & Identity',
    userRoles: ['Customer'],
    description: 'Allows a new or existing customer to register/login by providing name, phone, optional email, address, and profile picture URL. Creates customer record and returns JWT pair.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/customers/register'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Customer', 'RefreshToken'],
    sourceFiles: ['src/features/customer/customerRoutes.ts', 'src/features/customer/customerController.ts', 'src/features/customer/customer.service.ts'],
    runtimeVerified: true,
    notes: ['Validates 10-digit Indian phone format; handles upsert/conflict']
  },
  {
    id: 'AUTH-002',
    name: 'Worker Registration & Onboarding',
    category: 'Authentication & Identity',
    userRoles: ['Worker'],
    description: 'Allows a worker to register by phone number with basic profile details (name, skill category, daily rate). Enforces phone uniqueness and initializes worker in PENDING_VERIFICATION state.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/workers/register'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Worker', 'RefreshToken'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts', 'src/features/worker/worker.service.ts'],
    runtimeVerified: true,
    notes: ['Enforces unique phone index']
  },
  {
    id: 'AUTH-003',
    name: 'Unified Phone OTP Request',
    category: 'Authentication & Identity',
    userRoles: ['Customer', 'Worker'],
    description: 'Generates a 6-digit cryptographic OTP, stores hashed value in Redis with 5-minute TTL, and enforces sliding window rate limiting (max 5 OTPs per 10 minutes per phone). Dispatches SMS via provider.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/auth/otp/send'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['User'],
    sourceFiles: ['src/features/auth/auth.routes.ts', 'src/features/auth/auth.controller.ts', 'src/features/auth/auth.service.ts', 'src/features/auth/otp.service.ts'],
    runtimeVerified: true,
    notes: ['Redis atomic sliding window; mock OTP bypass available in non-production test mode']
  },
  {
    id: 'AUTH-004',
    name: 'Unified Phone OTP Verification & Login',
    category: 'Authentication & Identity',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Validates submitted OTP against Redis hash with constant-time comparison, invalidates OTP upon successful verification, resolves user role, creates a new session in RefreshToken table, and issues short-lived JWT access token (15m) and refresh token (7d).',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/auth/otp/verify'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Customer', 'Worker', 'Admin', 'RefreshToken'],
    sourceFiles: ['src/features/auth/auth.routes.ts', 'src/features/auth/auth.controller.ts', 'src/features/auth/auth.service.ts', 'src/features/auth/session.service.ts'],
    runtimeVerified: true,
    notes: ['Constant-time hash comparison prevents timing side-channels']
  },
  {
    id: 'AUTH-005',
    name: 'Customer Direct Login',
    category: 'Authentication & Identity',
    userRoles: ['Customer'],
    description: 'Direct login endpoint for customers with existing registered phone number.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/customers/login'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Customer', 'RefreshToken'],
    sourceFiles: ['src/features/customer/customerRoutes.ts', 'src/features/customer/customerController.ts'],
    runtimeVerified: true,
    notes: ['Alternative to OTP verify for pre-authenticated/test flows']
  },
  {
    id: 'AUTH-006',
    name: 'Worker Direct Login',
    category: 'Authentication & Identity',
    userRoles: ['Worker'],
    description: 'Direct login endpoint for workers by phone number.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/workers/login'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Worker', 'RefreshToken'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts'],
    runtimeVerified: true,
    notes: ['Returns worker profile and tokens']
  },
  {
    id: 'AUTH-007',
    name: 'Refresh Token Rotation with Reuse Detection',
    category: 'Authentication & Identity',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Rotates an active refresh token: marks old token used, creates child token in family. If an already-used token is presented (potential token theft), revokes entire token family immediately.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/auth/refresh'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['RefreshToken'],
    sourceFiles: ['src/features/auth/auth.routes.ts', 'src/features/auth/auth.controller.ts', 'src/features/auth/session.service.ts'],
    runtimeVerified: true,
    notes: ['Family-based token replay detection implemented']
  },
  {
    id: 'AUTH-008',
    name: 'User Logout & Session Revocation',
    category: 'Authentication & Identity',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Revokes the presented refresh token and blacklists the active JWT access token in Redis until its natural expiration.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/auth/logout'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['RefreshToken'],
    sourceFiles: ['src/features/auth/auth.routes.ts', 'src/features/auth/auth.controller.ts', 'src/features/auth/session.service.ts'],
    runtimeVerified: true,
    notes: ['Dual invalidation: DB record revoked + Redis token blacklist']
  },
  {
    id: 'AUTH-009',
    name: 'Session Family Audit & Remote Revocation',
    category: 'Authentication & Identity',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Allows an authenticated user to list all active login sessions/devices and terminate individual sessions or all other sessions.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/auth/sessions', 'DELETE /api/auth/sessions/:sessionId', 'DELETE /api/auth/sessions/other'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['RefreshToken'],
    sourceFiles: ['src/features/auth/auth.routes.ts', 'src/features/auth/auth.controller.ts', 'src/features/auth/session.service.ts'],
    runtimeVerified: true,
    notes: ['Enforces user isolation on session management']
  },

  // ----------------------------------------------------
  // B. CUSTOMER FUNCTIONALITY
  // ----------------------------------------------------
  {
    id: 'CUST-001',
    name: 'Customer Profile Retrieval & Update',
    category: 'Customer Functionality',
    userRoles: ['Customer'],
    description: 'Fetches the current authenticated customer profile and allows updating name, email, address, and profile picture.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/customers/me', 'PUT /api/customers/me'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Customer'],
    sourceFiles: ['src/features/customer/customerRoutes.ts', 'src/features/customer/customerController.ts'],
    runtimeVerified: true,
    notes: ['Guarded by authenticateCustomer middleware']
  },
  {
    id: 'CUST-002',
    name: 'Customer FCM Device Registration & Revocation',
    category: 'Customer Functionality',
    userRoles: ['Customer'],
    description: 'Registers mobile FCM device tokens for push notifications with device type and app version, and allows revoking tokens on logout.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/customers/me/devices', 'DELETE /api/customers/me/devices/:token'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['CustomerDevice'],
    sourceFiles: ['src/features/customer/customerRoutes.ts', 'src/features/customer/customerController.ts'],
    runtimeVerified: true,
    notes: ['Supports multi-device token management']
  },
  {
    id: 'CUST-003',
    name: 'Customer Notification Inbox & Acknowledgment',
    category: 'Customer Functionality',
    userRoles: ['Customer'],
    description: 'Fetches persistent notification history for customer with unread count and allows marking notifications as read/acknowledged.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/customers/notifications', 'POST /api/customers/notifications/:id/ack', 'POST /api/customers/notifications/read-all'],
    socketEvents: ['notification:sync', 'notification:ack'],
    backgroundJobs: [],
    databaseModels: ['Notification'],
    sourceFiles: ['src/features/customer/customerRoutes.ts', 'src/features/customer/customerController.ts', 'src/socket/socketHandlers.ts'],
    runtimeVerified: true,
    notes: ['Synchronized across HTTP API and Socket.IO']
  },

  // ----------------------------------------------------
  // C. WORKER FUNCTIONALITY & ONBOARDING
  // ----------------------------------------------------
  {
    id: 'WRK-001',
    name: 'Worker Profile Management',
    category: 'Worker Functionality',
    userRoles: ['Worker'],
    description: 'Fetches current worker profile, skills, documents status, verification badge, and allows updating operational parameters (daily rate, experience, bio).',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/workers/me', 'PUT /api/workers/me'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Worker', 'WorkerSkill'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts', 'src/features/worker/worker.service.ts'],
    runtimeVerified: true,
    notes: ['Guarded by authenticateWorker middleware']
  },
  {
    id: 'WRK-002',
    name: 'Worker Online/Offline Status Toggle',
    category: 'Worker Functionality',
    userRoles: ['Worker'],
    description: 'Sets worker status to ONLINE or OFFLINE. When going ONLINE, verifies that worker is APPROVED/ACTIVE and has an active location.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['PUT /api/workers/me/online'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Worker'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts', 'src/features/worker/worker.service.ts'],
    runtimeVerified: true,
    notes: ['Directly controls eligibility for dispatch matching']
  },
  {
    id: 'WRK-003',
    name: 'Worker Document Upload Flow',
    category: 'Worker Functionality',
    userRoles: ['Worker'],
    description: 'Generates secure pre-signed PUT upload URL for identity documents (AADHAAR, PAN, DRIVING_LICENSE, POLICE_VERIFICATION), registers document record in PENDING state.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/workers/me/upload-url', 'POST /api/workers/me/documents'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['WorkerDocument', 'Worker'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts', 'src/features/worker/worker.service.ts', 'src/providers/storage/localStorageProvider.ts'],
    runtimeVerified: true,
    notes: ['Storage provider generates HMAC-signed upload URLs; transitions worker verificationStatus']
  },
  {
    id: 'WRK-004',
    name: 'Worker Document View URL Generation',
    category: 'Worker Functionality',
    userRoles: ['Worker'],
    description: 'Generates a time-limited HMAC-signed GET URL for the worker to securely preview their own uploaded identity documents.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/workers/me/documents/:id/access-url'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['WorkerDocument'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts', 'src/providers/storage/localStorageProvider.ts'],
    runtimeVerified: true,
    notes: ['Enforces worker ownership of requested document']
  },
  {
    id: 'WRK-005',
    name: 'Worker Booking History & Schedule',
    category: 'Worker Functionality',
    userRoles: ['Worker'],
    description: 'Returns paginated list of worker bookings filtered by status (CONFIRMED, IN_PROGRESS, COMPLETED, CANCELLED).',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/workers/me/bookings'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Booking', 'Job', 'Customer'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts'],
    runtimeVerified: true,
    notes: ['Includes customer name, job details, and OTP requirements']
  },
  {
    id: 'WRK-006',
    name: 'Worker Earnings & Analytics',
    category: 'Worker Functionality',
    userRoles: ['Worker'],
    description: 'Computes worker completed jobs count, total gross earnings, platform commission deductions, and pending payouts.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/workers/me/earnings', 'GET /api/workers/me/analytics'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Booking', 'Payment'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts', 'src/features/worker/worker.service.ts'],
    runtimeVerified: true,
    notes: ['Calculates metrics from completed bookings and payment records']
  },
  {
    id: 'WRK-007',
    name: 'Worker Device Registration & Revocation',
    category: 'Worker Functionality',
    userRoles: ['Worker'],
    description: 'Registers worker FCM device tokens for real-time dispatch alerts and push notifications, and allows token deregistration.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/workers/me/devices', 'DELETE /api/workers/me/devices/:token'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['WorkerDevice'],
    sourceFiles: ['src/features/worker/workerRoutes.ts', 'src/features/worker/workerController.ts'],
    runtimeVerified: true,
    notes: ['Ensures worker receives job dispatch notifications']
  },

  // ----------------------------------------------------
  // D. JOBS & REQUIREMENTS
  // ----------------------------------------------------
  {
    id: 'JOB-001',
    name: 'Customer Job Creation with Requirements & Demands',
    category: 'Jobs & Requirements',
    userRoles: ['Customer'],
    description: 'Creates a job draft or published job with location coordinates, address, schedule (immediate vs scheduled), and nested skill requirements specifying headcount and wage per worker. Runs in Prisma transaction.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/jobs'],
    socketEvents: [],
    backgroundJobs: ['dispatch-queue'],
    databaseModels: ['Job', 'JobRequirement', 'JobDemand'],
    sourceFiles: ['src/features/jobs/jobRoutes.ts', 'src/features/jobs/jobController.ts', 'src/features/jobs/job.service.ts'],
    runtimeVerified: true,
    notes: ['Triggers dispatch wave job creation if autoDispatch is enabled']
  },
  {
    id: 'JOB-002',
    name: 'Customer Job Listing & History',
    category: 'Jobs & Requirements',
    userRoles: ['Customer'],
    description: 'Retrieves all jobs created by authenticated customer with status filtering, requirement fulfillment counts, and active bookings.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/jobs/my-jobs'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Job', 'JobRequirement', 'Booking'],
    sourceFiles: ['src/features/jobs/jobRoutes.ts', 'src/features/jobs/jobController.ts'],
    runtimeVerified: true,
    notes: ['Paginated, sorted by creation date descending']
  },
  {
    id: 'JOB-003',
    name: 'Job Detail Inspection',
    category: 'Jobs & Requirements',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Fetches granular job details including requirements, filled worker slots, start OTP, and linked bookings. Enforces role-based visibility (workers can only view if dispatched or booked).',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/jobs/:id'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Job', 'JobRequirement', 'Booking', 'Worker'],
    sourceFiles: ['src/features/jobs/jobRoutes.ts', 'src/features/jobs/jobController.ts', 'src/features/jobs/job.service.ts'],
    runtimeVerified: true,
    notes: ['Start OTP is masked for workers until booking is confirmed']
  },
  {
    id: 'JOB-004',
    name: 'Job Requirement Dynamic Management',
    category: 'Jobs & Requirements',
    userRoles: ['Customer'],
    description: 'Allows customer to add additional skill requirements or update headcounts on an active, unfilled job.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/jobs/:id/requirements', 'PUT /api/jobs/requirements/:reqId'],
    socketEvents: [],
    backgroundJobs: ['dispatch-queue'],
    databaseModels: ['JobRequirement', 'JobDemand'],
    sourceFiles: ['src/features/jobs/jobRoutes.ts', 'src/features/jobs/jobController.ts'],
    runtimeVerified: true,
    notes: ['Disallows modification if requirement is already fully filled or booking started']
  },
  {
    id: 'JOB-005',
    name: 'Customer Job Cancellation',
    category: 'Jobs & Requirements',
    userRoles: ['Customer'],
    description: 'Cancels a job if it has not started. Automatically cancels all pending dispatches, releases worker locks, updates all associated bookings to CANCELLED, and emits notification events.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/jobs/:id/cancel'],
    socketEvents: ['job:closed'],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['Job', 'JobRequirement', 'Booking', 'DispatchWaveWorker'],
    sourceFiles: ['src/features/jobs/jobRoutes.ts', 'src/features/jobs/jobController.ts', 'src/features/jobs/job.service.ts'],
    runtimeVerified: true,
    notes: ['Atomic transaction; releases pending worker dispatch locks']
  },

  // ----------------------------------------------------
  // E. WORKER LOCATION & TRACKING
  // ----------------------------------------------------
  {
    id: 'LOC-001',
    name: 'Worker Location Ingestion via HTTP',
    category: 'Worker Location & Tracking',
    userRoles: ['Worker'],
    description: 'Ingests worker GPS latitude/longitude, validates coordinate bounds (-90 to +90, -180 to +180), updates worker PostGIS geometry point and lastLocationAt timestamp, and records audit breadcrumb.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/worker_location/add', 'PUT /api/workers/me/location'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Worker', 'WorkerLocation'],
    sourceFiles: ['src/features/worker_location/worker_location.routes.ts', 'src/features/worker/workerRoutes.ts', 'src/features/worker_location/worker_location.service.ts'],
    runtimeVerified: true,
    notes: ['Updates PostGIS Point(lon, lat, 4326); verified in PostgreSQL']
  },
  {
    id: 'LOC-002',
    name: 'Worker Real-Time Location Stream via Socket.IO',
    category: 'Worker Location & Tracking',
    userRoles: ['Worker'],
    description: 'Worker sends real-time GPS coordinates over websocket event worker:location_update. Broadcasts coordinate to customer room booking:<bookingId> if worker is currently engaged in an active booking.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: ['worker:location_update', 'worker:location'],
    backgroundJobs: [],
    databaseModels: ['Worker', 'WorkerLocation'],
    sourceFiles: ['src/socket/socketHandlers.ts', 'src/features/worker_location/worker_location.service.ts'],
    runtimeVerified: true,
    notes: ['Broadcasting scoped strictly to customers holding active bookings with that worker']
  },
  {
    id: 'LOC-003',
    name: 'Customer Live Worker Tracking Endpoint',
    category: 'Worker Location & Tracking',
    userRoles: ['Customer'],
    description: 'Allows customer to fetch current GPS coordinates, accuracy, and last updated timestamp for the worker assigned to their active booking.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/bookings/:id/worker-location'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Booking', 'Worker'],
    sourceFiles: ['src/features/booking/bookingRoutes.ts', 'src/features/booking/bookingController.ts'],
    runtimeVerified: true,
    notes: ['Guarded by booking customer authorization']
  },

  // ----------------------------------------------------
  // F. DISPATCH & MATCHING ENGINE
  // ----------------------------------------------------
  {
    id: 'DISP-001',
    name: 'PostGIS Radial Worker Matching Query',
    category: 'Dispatch & Matching',
    userRoles: ['System'],
    description: 'Queries eligible workers using PostGIS ST_DWithin geography index, filtering by active skill ID, status ONLINE, verificationStatus APPROVED, not currently in active booking, and location freshness (<30m). Orders by distance ascending.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: [],
    backgroundJobs: ['dispatch-queue'],
    databaseModels: ['Worker', 'WorkerSkill', 'WorkerLocation'],
    sourceFiles: ['src/features/dispatch/dispatchService.ts', 'src/features/dispatch/dispatchRepository.ts'],
    runtimeVerified: true,
    notes: ['PostGIS ST_DWithin spatial index verified against Supabase PostgreSQL']
  },
  {
    id: 'DISP-002',
    name: 'Wave-Based Dispatch Orchestration with Timeout Queue',
    category: 'Dispatch & Matching',
    userRoles: ['System'],
    description: 'Dispatches job requirements in concentric or tiered waves (batch of K workers per slot). Schedules a BullMQ timeout job (e.g. 60s per wave). If wave expires without acceptance, next wave is triggered until radius or candidate pool exhausted.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: ['job:incoming'],
    backgroundJobs: ['dispatch-queue', 'timeout-queue'],
    databaseModels: ['DispatchWave', 'DispatchWaveWorker'],
    sourceFiles: ['src/features/dispatch/dispatchService.ts', 'src/features/dispatch/dispatchWorker.ts', 'src/features/dispatch/timeoutWorker.ts'],
    runtimeVerified: true,
    notes: ['Dual alerting: Emits job:incoming Socket.IO event and enqueues FCM push notification']
  },
  {
    id: 'DISP-003',
    name: 'Worker Incoming Dispatch Poll & Detail',
    category: 'Dispatch & Matching',
    userRoles: ['Worker'],
    description: 'Allows worker to poll current active dispatches addressed to them, view job location, estimated distance, wage, and remaining response time.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/dispatch/incoming', 'GET /api/dispatch/:id'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['DispatchWaveWorker', 'Job', 'JobRequirement'],
    sourceFiles: ['src/features/dispatch/dispatchRoutes.ts', 'src/features/dispatch/dispatchController.ts'],
    runtimeVerified: true,
    notes: ['Filters out expired or cancelled waves']
  },
  {
    id: 'DISP-004',
    name: 'Worker Dispatch Acceptance & Atomic Booking Creation',
    category: 'Dispatch & Matching',
    userRoles: ['Worker'],
    description: 'Worker accepts incoming dispatch. Executes inside serializable/isolated transaction: checks slot availability, marks dispatch ACCEPTED, cancels competing dispatches in wave, generates start OTP, creates Booking, updates requirement filled count. If requirement full, marks requirement/job FULFILLED.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/dispatch/:id/accept'],
    socketEvents: ['job:closed'],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['DispatchWaveWorker', 'Booking', 'JobRequirement', 'Job', 'Worker'],
    sourceFiles: ['src/features/dispatch/dispatchRoutes.ts', 'src/features/dispatch/dispatchController.ts', 'src/features/dispatch/dispatchService.ts'],
    runtimeVerified: true,
    notes: ['Fully atomic transaction prevents double-booking of requirement slots']
  },
  {
    id: 'DISP-005',
    name: 'Worker Dispatch Decline / Rejection',
    category: 'Dispatch & Matching',
    userRoles: ['Worker'],
    description: 'Worker explicitly declines a dispatch offer. Marks DispatchWaveWorker REJECTED and checks if wave needs early advancement to next candidate.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/dispatch/:id/decline'],
    socketEvents: [],
    backgroundJobs: ['dispatch-queue'],
    databaseModels: ['DispatchWaveWorker'],
    sourceFiles: ['src/features/dispatch/dispatchRoutes.ts', 'src/features/dispatch/dispatchController.ts'],
    runtimeVerified: true,
    notes: ['Frees wave slot early instead of waiting for timeout']
  },
  {
    id: 'DISP-006',
    name: 'Automated Dispatch Reconciliation & Orphan Recovery',
    category: 'Dispatch & Matching',
    userRoles: ['System'],
    description: 'Scheduled background task running every 30 seconds that scans for expired dispatch waves with unhandled timeouts or lost BullMQ jobs, marks them EXPIRED, and advances the wave engine.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: [],
    backgroundJobs: ['dispatch-reconciliation'],
    databaseModels: ['DispatchWave', 'DispatchWaveWorker'],
    sourceFiles: ['src/features/dispatch/dispatchReconciliationService.ts', 'src/lifecycle/lifecycleManager.ts'],
    runtimeVerified: true,
    notes: ['Self-healing background worker prevents stuck dispatches']
  },

  // ----------------------------------------------------
  // G. BOOKINGS & LIFECYCLE
  // ----------------------------------------------------
  {
    id: 'BKG-001',
    name: 'Booking Detail Inspection',
    category: 'Bookings & Lifecycle',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Retrieves booking details including customer contact, worker profile, scheduled time, current status, agreed rate, and payment status.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/bookings/:id'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Booking', 'Job', 'Customer', 'Worker', 'Payment'],
    sourceFiles: ['src/features/booking/bookingRoutes.ts', 'src/features/booking/bookingController.ts', 'src/features/booking/bookingService.ts'],
    runtimeVerified: true,
    notes: ['Authorizes only participating customer, assigned worker, or admin']
  },
  {
    id: 'BKG-002',
    name: 'Worker Arrival & Start Job via Customer OTP Verification',
    category: 'Bookings & Lifecycle',
    userRoles: ['Worker'],
    description: 'Worker arrives at job site and submits customer start OTP. Backend verifies OTP against booking record, transitions booking state from CONFIRMED to IN_PROGRESS, sets startedAt timestamp, and records audit trail.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/bookings/:id/start'],
    socketEvents: ['booking:started'],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['Booking'],
    sourceFiles: ['src/features/booking/bookingRoutes.ts', 'src/features/booking/bookingController.ts', 'src/features/booking/bookingService.ts'],
    runtimeVerified: true,
    notes: ['Enforces OTP verification before work can legally commence']
  },
  {
    id: 'BKG-003',
    name: 'Worker Job Completion Submission',
    category: 'Bookings & Lifecycle',
    userRoles: ['Worker'],
    description: 'Worker signals work completed. Backend transitions booking status to WORKER_COMPLETED or PENDING_CUSTOMER_CONFIRMATION and notifies customer to inspect work and release payment.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/bookings/:id/worker-complete', 'POST /api/bookings/:id/complete'],
    socketEvents: ['booking:completed'],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['Booking'],
    sourceFiles: ['src/features/booking/bookingRoutes.ts', 'src/features/booking/bookingController.ts', 'src/features/booking/bookingService.ts'],
    runtimeVerified: true,
    notes: ['Triggers notification to customer for confirmation and review']
  },
  {
    id: 'BKG-004',
    name: 'Customer Completion Confirmation & Rating Prompt',
    category: 'Bookings & Lifecycle',
    userRoles: ['Customer'],
    description: 'Customer accepts worker completion. Sets booking status to COMPLETED, marks finishedAt timestamp, releases worker to ONLINE/IDLE, and prompts for worker rating/review.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/bookings/:id/customer-confirm'],
    socketEvents: ['booking:confirmed_complete'],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['Booking', 'Worker'],
    sourceFiles: ['src/features/booking/bookingRoutes.ts', 'src/features/booking/bookingController.ts'],
    runtimeVerified: true,
    notes: ['Finalizes booking lifecycle']
  },
  {
    id: 'BKG-005',
    name: 'Booking Cancellation with Penalty/Reason Handling',
    category: 'Bookings & Lifecycle',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Cancels an active booking before start. Records cancellation reason and cancelledBy actor, frees worker back to ONLINE, and emits real-time cancellation alert.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/bookings/:id/cancel'],
    socketEvents: ['booking:cancelled'],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['Booking', 'Worker'],
    sourceFiles: ['src/features/booking/bookingRoutes.ts', 'src/features/booking/bookingController.ts', 'src/features/booking/bookingService.ts'],
    runtimeVerified: true,
    notes: ['Rejects cancellation if booking is already IN_PROGRESS or COMPLETED']
  },

  // ----------------------------------------------------
  // H. PAYMENTS & RAZORPAY INTEGRATION
  // ----------------------------------------------------
  {
    id: 'PAY-001',
    name: 'Razorpay Order Creation for Booking',
    category: 'Payments & Billing',
    userRoles: ['Customer'],
    description: 'Calculates booking payable amount (wage + platform fee + tax), creates a cryptographic Razorpay Order via SDK, and stores initial Payment record with status PENDING.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/payments/create-order'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Payment', 'Booking'],
    sourceFiles: ['src/features/payment/paymentRoutes.ts', 'src/features/payment/paymentController.ts', 'src/features/payment/payment.service.ts'],
    runtimeVerified: true,
    notes: ['Returns razorpayOrderId, currency, and keyId to mobile client']
  },
  {
    id: 'PAY-002',
    name: 'Razorpay Webhook Ingestion & Signature Verification',
    category: 'Payments & Billing',
    userRoles: ['System'],
    description: 'Receives asynchronous Razorpay webhooks (order.paid, payment.captured, payment.failed). Validates webhook HMAC SHA-256 signature using raw request body, updates Payment status to SUCCESS/FAILED, and updates Booking paymentStatus to PAID.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/payments/webhook'],
    socketEvents: [],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['Payment', 'Booking'],
    sourceFiles: ['src/features/payment/paymentRoutes.ts', 'src/features/payment/paymentController.ts', 'src/features/payment/payment.service.ts'],
    runtimeVerified: true,
    notes: ['Configured with express.raw middleware to ensure accurate HMAC byte calculation']
  },
  {
    id: 'PAY-003',
    name: 'Booking Payment Status Query',
    category: 'Payments & Billing',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Retrieves payment status, transaction reference, amount, and receipt for a given booking.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/payments/booking/:bookingId', 'GET /api/bookings/:id/payment'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Payment'],
    sourceFiles: ['src/features/payment/paymentRoutes.ts', 'src/features/booking/bookingRoutes.ts'],
    runtimeVerified: true,
    notes: ['Provides payment verification for clients']
  },
  {
    id: 'PAY-004',
    name: 'Payment Refund Initiation (Database State Only)',
    category: 'Payments & Billing',
    userRoles: ['Admin'],
    description: 'Marks payment record as REFUNDED in database upon cancellation. NOTE: Currently does not dispatch the live Razorpay API refund call (gateway call stubbed/deferred).',
    status: 'PARTIALLY_IMPLEMENTED',
    evidenceLevel: 'C',
    httpEndpoints: ['POST /api/payments/:bookingId/refund'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Payment'],
    sourceFiles: ['src/features/payment/paymentRoutes.ts', 'src/features/payment/paymentController.ts'],
    runtimeVerified: false,
    notes: ['Known release gap: DB updated to REFUNDED but Razorpay Refund SDK call not yet wired']
  },
  {
    id: 'PAY-005',
    name: 'Payment Reconciliation Worker',
    category: 'Payments & Billing',
    userRoles: ['System'],
    description: 'Background worker running on payment-reconciliation queue that handles stuck pending payments and verifies gateway statuses.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: [],
    backgroundJobs: ['payment-reconciliation'],
    databaseModels: ['Payment'],
    sourceFiles: ['src/workers/paymentReconciliationWorker.ts', 'src/lifecycle/lifecycleManager.ts'],
    runtimeVerified: true,
    notes: ['Started in lifecycleManager']
  },

  // ----------------------------------------------------
  // I. CHAT & REALTIME COMMUNICATION
  // ----------------------------------------------------
  {
    id: 'CHAT-001',
    name: 'Booking In-App Chat over Socket.IO',
    category: 'Chat & Realtime',
    userRoles: ['Customer', 'Worker'],
    description: 'Real-time peer-to-peer messaging between customer and worker within an active booking. Validates membership in booking room, persists message to ChatMessage table, and broadcasts to room booking:<id>.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: ['chat:message', 'join:booking', 'join:chat'],
    backgroundJobs: [],
    databaseModels: ['ChatMessage', 'Booking'],
    sourceFiles: ['src/socket/socketHandlers.ts', 'src/features/chat/chat.service.ts'],
    runtimeVerified: true,
    notes: ['Enforces authorization: only customer or worker associated with the booking can join room']
  },
  {
    id: 'CHAT-002',
    name: 'Historical Chat Message Fetch via HTTP',
    category: 'Chat & Realtime',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Fetches paginated chat message history for a booking with sender identity, timestamps, and read indicators.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/chat/booking/:bookingId'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['ChatMessage'],
    sourceFiles: ['src/features/chat/chatRoutes.ts', 'src/features/chat/chatController.ts'],
    runtimeVerified: true,
    notes: ['Includes rate limiting and ownership validation']
  },
  {
    id: 'CHAT-003',
    name: 'HTTP Fallback Chat Message Send',
    category: 'Chat & Realtime',
    userRoles: ['Customer', 'Worker'],
    description: 'Allows sending chat message via REST API when websocket connection is degraded. Stores message and triggers notification.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/chat/send'],
    socketEvents: ['chat:message'],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['ChatMessage'],
    sourceFiles: ['src/features/chat/chatRoutes.ts', 'src/features/chat/chatController.ts'],
    runtimeVerified: true,
    notes: ['Mirrors socket persistence and emits socket event to room']
  },

  // ----------------------------------------------------
  // J. NOTIFICATIONS & OUTBOX ENGINE
  // ----------------------------------------------------
  {
    id: 'NOTIF-001',
    name: 'Transactional Outbox Notification Dispatch',
    category: 'Notifications',
    userRoles: ['System'],
    description: 'Application services write notification events to OutboxEvent table within the same DB transaction as business state changes. OutboxWorker polls pending events with lease locks and dispatches them.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: ['notification:<event>'],
    backgroundJobs: ['outbox-poller', 'notification-queue'],
    databaseModels: ['OutboxEvent', 'Notification'],
    sourceFiles: ['src/workers/outboxWorker.ts', 'src/features/notification/notificationService.ts', 'src/lifecycle/lifecycleManager.ts'],
    runtimeVerified: true,
    notes: ['Guarantees at-least-once notification dispatch; prevents dual-write anomalies']
  },
  {
    id: 'NOTIF-002',
    name: 'Firebase Cloud Messaging (FCM) Push Delivery',
    category: 'Notifications',
    userRoles: ['System'],
    description: 'Notification worker reads worker/customer device tokens and dispatches push notifications via Firebase Admin SDK. Prunes invalid/unregistered device tokens automatically.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: [],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['CustomerDevice', 'WorkerDevice'],
    sourceFiles: ['src/providers/notification/fcmProvider.ts', 'src/workers/notificationWorker.ts'],
    runtimeVerified: true,
    notes: ['Firebase Admin SDK initialized with staging service account credentials']
  },
  {
    id: 'NOTIF-003',
    name: 'Real-Time Socket.IO Notification Delivery',
    category: 'Notifications',
    userRoles: ['Customer', 'Worker'],
    description: 'Directly emits notification events to connected user personal rooms (customer:<id>, worker:<id>) for instant in-app alerts.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: ['notification:sync', 'notification:new'],
    backgroundJobs: [],
    databaseModels: ['Notification'],
    sourceFiles: ['src/socket/socketHandlers.ts', 'src/workers/notificationWorker.ts'],
    runtimeVerified: true,
    notes: ['Provides instant toast notifications while app is in foreground']
  },

  // ----------------------------------------------------
  // K. WORKER SKILLS & CANONICAL CATALOG
  // ----------------------------------------------------
  {
    id: 'SKILL-001',
    name: 'Canonical Skill Directory Browsing',
    category: 'Skills & Catalog',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Returns list of active canonical skills with category, baseline hourly rate, and description for job posting and worker profile selection.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/skill/list', 'GET /api/skill'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Skill'],
    sourceFiles: ['src/features/skill/skillRouter.ts', 'src/features/skill/skillController.ts'],
    runtimeVerified: true,
    notes: ['Public catalog; cached in memory/Redis']
  },
  {
    id: 'SKILL-002',
    name: 'Admin Skill Creation & Activation Toggle',
    category: 'Skills & Catalog',
    userRoles: ['Admin'],
    description: 'Allows administrators to register new trade skills into the marketplace catalog and activate or deactivate existing skills.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/skill/create', 'PATCH /api/skill/:id/toggle'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Skill'],
    sourceFiles: ['src/features/skill/skillRouter.ts', 'src/features/skill/skillController.ts'],
    runtimeVerified: true,
    notes: ['Guarded by authenticateAdmin middleware']
  },

  // ----------------------------------------------------
  // L. REVIEWS & RATINGS
  // ----------------------------------------------------
  {
    id: 'REV-001',
    name: 'Customer Review & Rating Submission',
    category: 'Reviews & Ratings',
    userRoles: ['Customer'],
    description: 'Customer submits a 1-5 star review with optional written feedback for a completed booking. Updates Worker aggregate rating and reviewCount inside an atomic transaction.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/reviews'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Review', 'Worker', 'Booking'],
    sourceFiles: ['src/features/review/reviewRoutes.ts', 'src/features/review/reviewController.ts', 'src/features/review/review.service.ts'],
    runtimeVerified: true,
    notes: ['Enforces unique review per booking; rejects duplicate submissions']
  },
  {
    id: 'REV-002',
    name: 'Worker Public Review Listing',
    category: 'Reviews & Ratings',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Fetches paginated list of verified customer reviews for a given worker profile.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/reviews/worker/:workerId', 'GET /api/reviews/booking/:bookingId'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Review', 'Customer'],
    sourceFiles: ['src/features/review/reviewRoutes.ts', 'src/features/review/reviewController.ts'],
    runtimeVerified: true,
    notes: ['Sanitizes customer personal identifiers']
  },

  // ----------------------------------------------------
  // M. ADMIN & GOVERNANCE
  // ----------------------------------------------------
  {
    id: 'ADM-001',
    name: 'Worker Directory & Verification Queue with Filters',
    category: 'Admin & Governance',
    userRoles: ['Admin'],
    description: 'Lists all workers with filters by verificationStatus (PENDING, APPROVED, REJECTED), status (ONLINE, OFFLINE, SUSPENDED), and skill.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/admin/workers'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Worker', 'WorkerDocument'],
    sourceFiles: ['src/features/admin/adminRoutes.ts', 'src/features/admin/adminController.ts'],
    runtimeVerified: true,
    notes: ['Strictly guarded by authenticateAdmin']
  },
  {
    id: 'ADM-002',
    name: 'Worker Document Inspection via Admin Signed URL',
    category: 'Admin & Governance',
    userRoles: ['Admin'],
    description: 'Generates secure HMAC-signed download URL for admin auditors to inspect submitted KYC documents (Aadhaar/PAN/license).',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/admin/workers/:workerId/documents/:docId/access-url', 'GET /api/admin/workers/:id/documents'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['WorkerDocument'],
    sourceFiles: ['src/features/admin/adminRoutes.ts', 'src/features/admin/adminController.ts', 'src/providers/storage/localStorageProvider.ts'],
    runtimeVerified: true,
    notes: ['Admin can inspect private files without exposing storage keys']
  },
  {
    id: 'ADM-003',
    name: 'Worker Document KYC Verification / Rejection',
    category: 'Admin & Governance',
    userRoles: ['Admin'],
    description: 'Admin approves or rejects a worker document with rejection reason. If all mandatory documents are approved, automatically updates worker verificationStatus to APPROVED.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/admin/workers/:workerId/documents/:docId/verify'],
    socketEvents: [],
    backgroundJobs: ['notification-queue'],
    databaseModels: ['WorkerDocument', 'Worker'],
    sourceFiles: ['src/features/admin/adminRoutes.ts', 'src/features/admin/adminController.ts', 'src/features/admin/admin.service.ts'],
    runtimeVerified: true,
    notes: ['Triggers notification to worker regarding verification result']
  },
  {
    id: 'ADM-004',
    name: 'Worker Account Suspension & Reinstatement',
    category: 'Admin & Governance',
    userRoles: ['Admin'],
    description: 'Suspends an abusive worker account or reinstates an existing worker. Suspended workers are immediately booted offline and disqualified from dispatch matching.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['POST /api/admin/workers/:id/suspend', 'POST /api/admin/workers/:id/reinstate'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Worker', 'RefreshToken'],
    sourceFiles: ['src/features/admin/adminRoutes.ts', 'src/features/admin/adminController.ts'],
    runtimeVerified: true,
    notes: ['Immediately invalidates worker session tokens']
  },
  {
    id: 'ADM-005',
    name: 'System-Wide Marketplace Job & Booking Monitoring',
    category: 'Admin & Governance',
    userRoles: ['Admin'],
    description: 'Admin dashboard endpoint listing all platform jobs and bookings with status filters, date range filters, and anomaly flags.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/admin/jobs', 'GET /api/admin/flagged-workers'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['Job', 'Booking', 'Worker'],
    sourceFiles: ['src/features/admin/adminRoutes.ts', 'src/features/admin/adminController.ts'],
    runtimeVerified: true,
    notes: ['Enables operational oversight']
  },
  {
    id: 'ADM-006',
    name: 'Admin Audit Log Retrieval',
    category: 'Admin & Governance',
    userRoles: ['Admin'],
    description: 'Fetches immutable audit log entries recording administrative interventions, document approvals, and state overrides.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /api/admin/audit-logs'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: ['AuditLog'],
    sourceFiles: ['src/features/admin/adminRoutes.ts', 'src/features/admin/adminController.ts'],
    runtimeVerified: true,
    notes: ['Provides governance compliance trail']
  },

  // ----------------------------------------------------
  // N. OBJECT STORAGE & SIGNED URLS
  // ----------------------------------------------------
  {
    id: 'STOR-001',
    name: 'HMAC Signed Object Upload & Download Service',
    category: 'Storage & Documents',
    userRoles: ['Customer', 'Worker', 'Admin'],
    description: 'Provides signed URL endpoints (/download/:key, /upload/:key, /api/storage/signed-url) that validate cryptographic signatures with expiry timestamps before streaming files to/from local or S3-compatible storage.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /download/:key', 'PUT /upload/:key', 'POST /api/storage/signed-url'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: [],
    sourceFiles: ['src/providers/storage/storage.routes.ts', 'src/providers/storage/localStorageProvider.ts', 'src/server.ts'],
    runtimeVerified: true,
    notes: ['Secures private worker KYC documents from unauthorized direct downloads']
  },

  // ----------------------------------------------------
  // O. OPERATIONAL, METRICS & HEALTH
  // ----------------------------------------------------
  {
    id: 'OPS-001',
    name: 'Liveness & Readiness Health Probes',
    category: 'Operational & Health',
    userRoles: ['System', 'Admin'],
    description: 'Provides Kubernetes-standard /health/live and /health/ready probes that verify PostgreSQL database connection, Redis ping, BullMQ worker status, and memory thresholds.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /health', 'GET /health/live', 'GET /health/ready'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: [],
    sourceFiles: ['src/features/health/healthRoutes.ts', 'src/features/health/healthController.ts', 'src/server.ts'],
    runtimeVerified: true,
    notes: ['Returns 200 OK or 503 Service Unavailable']
  },
  {
    id: 'OPS-002',
    name: 'Prometheus Metrics Exposition',
    category: 'Operational & Health',
    userRoles: ['System', 'Admin'],
    description: 'Exposes standard Prometheus metrics (/metrics) for HTTP request duration, error rates, database connection pool stats, and active websocket connections.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: ['GET /metrics'],
    socketEvents: [],
    backgroundJobs: [],
    databaseModels: [],
    sourceFiles: ['src/server.ts'],
    runtimeVerified: true,
    notes: ['Standard Prometheus format output']
  },
  {
    id: 'OPS-003',
    name: 'Daily Location & Stale OTP Cleanup Cron',
    category: 'Operational & Health',
    userRoles: ['System'],
    description: 'Background cron job running daily to purge worker location breadcrumbs older than 30 days and delete expired OTP records.',
    status: 'IMPLEMENTED',
    evidenceLevel: 'B',
    httpEndpoints: [],
    socketEvents: [],
    backgroundJobs: ['cleanup-cron'],
    databaseModels: ['WorkerLocation'],
    sourceFiles: ['src/lifecycle/lifecycleManager.ts'],
    runtimeVerified: true,
    notes: ['Maintains database size bounds and compliance with data retention policies']
  }
];

const targetPath = path.resolve(__dirname, '..', 'LABOURBABA_ACTUAL_FEATURES.json');
fs.writeFileSync(targetPath, JSON.stringify(features, null, 2), 'utf8');
console.log(`Successfully generated ${targetPath} with ${features.length} audited features.`);
